openapi: 3.0.0
info:
  title: OMS - Admin API
  version: 1.0.0
  description: Admin-only endpoints for managing users, orders, products, and analytics
security:               
  - bearerAuth: []
tags:
  - name: AdminUsers
    description: User management by admins
  - name: AdminOrders
    description: Order management by admins
  - name: AdminProducts
    description: Product management by admins
  - name: AdminAnalytics
    description: Analytics & insights

paths:
  /api/admin/users:
    get:
      summary: Get all users
      tags: [AdminUsers]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: role
          schema:
            type: string
            enum: [buyer, supplier, admin]
        - in: query
          name: is_active
          schema:
            type: boolean
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Users retrieved successfully

  /api/admin/users/{id}:
    get:
      summary: Get user by ID
      tags: [AdminUsers]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: User details retrieved successfully
        404:
          description: User not found

    delete:
      summary: Delete user
      tags: [AdminUsers]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: User deleted successfully
        404:
          description: User not found

  /api/admin/users/{id}/status:
    patch:
      summary: Update user status
      tags: [AdminUsers]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [is_active]
              properties:
                is_active:
                  type: boolean
                  description: Whether the user is active
      responses:
        200:
          description: User status updated successfully
        400:
          description: Validation failed

  /api/admin/orders:
    get:
      summary: Get all orders
      tags: [AdminOrders]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [PENDING, APPROVED, FULFILLED, CANCELLED]
        - in: query
          name: supplier_id
          schema:
            type: string
            format: uuid
        - in: query
          name: buyer_id
          schema:
            type: string
            format: uuid
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Orders retrieved successfully

  /api/admin/orders/{id}:
    get:
      summary: Get order by ID
      tags: [AdminOrders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Order details retrieved successfully
        404:
          description: Order not found

  /api/admin/products:
    get:
      summary: Get all products
      tags: [AdminProducts]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: supplier_id
          schema:
            type: string
            format: uuid
        - in: query
          name: category
          schema:
            type: string
        - in: query
          name: in_stock
          schema:
            type: boolean
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Products retrieved successfully

  /api/admin/analytics:
    get:
      summary: Get analytics dashboard
      tags: [AdminAnalytics]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Analytics retrieved successfully

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
