openapi: 3.0.0
info:
  title: OMS - Buyer Order API
  version: 1.0.0
  description: Endpoints for buyers to manage their orders in the Order Management System

tags:
  - name: BuyerOrders
    description: Buyer-specific order management

paths:
  /api/buyer/orders:
    post:
      summary: Place a new order
      tags: [BuyerOrders]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                supplierId:
                  type: string
                  format: uuid
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                        format: uuid
                      quantity:
                        type: number
                      unitCode:
                        type: string
      responses:
        201:
          description: Order placed successfully
        400:
          description: Validation error
        401:
          description: Unauthorized

    get:
      summary: Get buyer's orders
      tags: [BuyerOrders]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [PENDING, CONFIRMED, CANCELLED, COMPLETED]
        - in: query
          name: page
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Orders retrieved successfully
        401:
          description: Unauthorized

  /api/buyer/orders/{id}:
    get:
      summary: Get order details with full history
      tags: [BuyerOrders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Order details retrieved successfully
        401:
          description: Unauthorized
        404:
          description: Order not found

  /api/buyer/orders/{id}/cancel:
    patch:
      summary: Cancel order
      tags: [BuyerOrders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
      responses:
        200:
          description: Order cancelled successfully
        400:
          description: Validation error
        401:
          description: Unauthorized
        404:
          description: Order not found

  /api/buyer/orders/statistics:
    get:
      summary: Get order statistics
      tags: [BuyerOrders]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Order statistics retrieved successfully
        401:
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
