openapi: 3.0.0
info:
  title: OMS - Seller Order API
  version: 1.0.0
  description: Endpoints for sellers (suppliers) to manage incoming orders in the Order Management System

tags:
  - name: SellerOrders
    description: Supplier-specific order management

paths:
  /api/seller/orders/{id}/status:
    patch:
      summary: Update order status (Approve, Fulfill, Cancel)
      tags: [SellerOrders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum: [APPROVED, FULFILLED, CANCELLED]
                reason:
                  type: string
                  description: Optional reason for cancellation or status change
      responses:
        200:
          description: Order status updated successfully
        400:
          description: Validation error
        401:
          description: Unauthorized
        404:
          description: Order not found

  /api/seller/orders/{id}:
    get:
      summary: Get order details
      tags: [SellerOrders]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Order details retrieved successfully
        401:
          description: Unauthorized
        404:
          description: Order not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
